{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "94185c1e",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'wandb'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[0;32mIn [6]\u001b[0m, in \u001b[0;36m<cell line: 26>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     24\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtensorflow\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mkeras\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mapplications\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m\n\u001b[1;32m     25\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodel_selection\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m train_test_split\n\u001b[0;32m---> 26\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mwandb\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mkeras\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m WandbCallback\n\u001b[1;32m     27\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mwandb\u001b[39;00m\n\u001b[1;32m     28\u001b[0m tf\u001b[38;5;241m.\u001b[39m__version__\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'wandb'"
     ]
    }
   ],
   "source": [
    "import warnings \n",
    "warnings.filterwarnings(action='ignore')\n",
    "import os \n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from glob import glob\n",
    "from tqdm.auto import tqdm\n",
    "import cv2\n",
    "\n",
    "# from tensorflow.keras.applications import Densnet\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.models import Sequential, Model\n",
    "from tensorflow.keras import layers\n",
    "import tensorflow.keras as keras\n",
    "from tensorflow.data import Dataset\n",
    "\n",
    "from tensorflow.keras.optimizers import Adam, RMSprop, Nadam, SGD\n",
    "from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping\n",
    "\n",
    "from itertools import product\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "\n",
    "from tensorflow.keras.applications import *\n",
    "from sklearn.model_selection import train_test_split\n",
    "from wandb.keras import WandbCallback\n",
    "import wandb\n",
    "tf.__version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "08327eb2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): done\n",
      "Solving environment: | \n",
      "The environment is inconsistent, please check the package plan carefully\n",
      "The following packages are causing the inconsistency:\n",
      "\n",
      "  - defaults/linux-64::tensorflow==2.4.1=mkl_py39h4683426_0\n",
      "  - defaults/linux-64::pandas==1.2.4=py39ha9443f7_0\n",
      "  - defaults/linux-64::matplotlib-base==3.4.3=py39hbbc1b5f_0\n",
      "  - defaults/linux-64::hdf5==1.10.6=hb1b8bf9_0\n",
      "  - defaults/linux-64::numpy-base==1.16.6=py39h41b4c56_3\n",
      "  - defaults/linux-64::bottleneck==1.3.4=py39hce1f21e_0\n",
      "  - defaults/noarch::tensorflow-estimator==2.6.0=pyh7b7c402_0\n",
      "  - defaults/linux-64::opencv==4.5.5=py39h905f02f_0\n",
      "  - defaults/linux-64::scipy==1.7.3=py39h492baa0_0\n",
      "  - defaults/linux-64::scikit-learn==1.0.2=py39h51133e4_1\n",
      "  - defaults/linux-64::libgfortran-ng==7.5.0=ha8ba4b0_17\n",
      "  - defaults/linux-64::libopenblas==0.3.18=hf726d26_0\n",
      "  - defaults/linux-64::numpy==1.16.6=py39h0a8e133_3\n",
      "  - defaults/linux-64::h5py==2.10.0=py39hec9cf62_0\n",
      "  - defaults/noarch::opt_einsum==3.3.0=pyhd3eb1b0_1\n",
      "  - defaults/linux-64::tensorflow-base==2.4.1=mkl_py39h43e0292_0\n",
      "  - defaults/linux-64::matplotlib==3.4.3=py39h06a4308_0\n",
      "  - defaults/noarch::tensorboard==2.4.0=pyhc547734_0\n",
      "  - defaults/noarch::keras-preprocessing==1.1.2=pyhd3eb1b0_0\n",
      "done\n",
      "\n",
      "\n",
      "==> WARNING: A newer version of conda exists. <==\n",
      "  current version: 4.8.4\n",
      "  latest version: 4.13.0\n",
      "\n",
      "Please update conda by running\n",
      "\n",
      "    $ conda update -n base -c defaults conda\n",
      "\n",
      "\n",
      "\n",
      "## Package Plan ##\n",
      "\n",
      "  environment location: /home/ubuntu/anaconda3/envs/why\n",
      "\n",
      "  added / updated specs:\n",
      "    - wandb\n",
      "\n",
      "\n",
      "The following packages will be downloaded:\n",
      "\n",
      "    package                    |            build\n",
      "    ---------------------------|-----------------\n",
      "    docker-pycreds-0.4.0       |             py_0          11 KB  conda-forge\n",
      "    gitdb-4.0.9                |     pyhd8ed1ab_0          46 KB  conda-forge\n",
      "    gitpython-3.1.27           |     pyhd8ed1ab_0         123 KB  conda-forge\n",
      "    pathtools-0.1.2            |             py_1           8 KB  conda-forge\n",
      "    promise-2.3                |   py39hf3d152e_6          36 KB  conda-forge\n",
      "    sentry-sdk-1.5.12          |     pyhd8ed1ab_0          90 KB  conda-forge\n",
      "    setproctitle-1.2.3         |   py39hb9d737c_0          16 KB  conda-forge\n",
      "    shortuuid-1.0.8            |   py39hf3d152e_0          17 KB  conda-forge\n",
      "    smmap-3.0.5                |     pyh44b312d_0          22 KB  conda-forge\n",
      "    wandb-0.12.18              |     pyhd8ed1ab_0         1.3 MB  conda-forge\n",
      "    ------------------------------------------------------------\n",
      "                                           Total:         1.7 MB\n",
      "\n",
      "The following NEW packages will be INSTALLED:\n",
      "\n",
      "  docker-pycreds     conda-forge/noarch::docker-pycreds-0.4.0-py_0\n",
      "  gitdb              conda-forge/noarch::gitdb-4.0.9-pyhd8ed1ab_0\n",
      "  gitpython          conda-forge/noarch::gitpython-3.1.27-pyhd8ed1ab_0\n",
      "  pathtools          conda-forge/noarch::pathtools-0.1.2-py_1\n",
      "  promise            conda-forge/linux-64::promise-2.3-py39hf3d152e_6\n",
      "  psutil             conda-forge/linux-64::psutil-5.9.1-py39hb9d737c_0\n",
      "  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39\n",
      "  pyyaml             conda-forge/linux-64::pyyaml-6.0-py39hb9d737c_4\n",
      "  sentry-sdk         conda-forge/noarch::sentry-sdk-1.5.12-pyhd8ed1ab_0\n",
      "  setproctitle       conda-forge/linux-64::setproctitle-1.2.3-py39hb9d737c_0\n",
      "  shortuuid          conda-forge/linux-64::shortuuid-1.0.8-py39hf3d152e_0\n",
      "  smmap              conda-forge/noarch::smmap-3.0.5-pyh44b312d_0\n",
      "  wandb              conda-forge/noarch::wandb-0.12.18-pyhd8ed1ab_0\n",
      "  yaml               conda-forge/linux-64::yaml-0.2.5-h7f98852_2\n",
      "\n",
      "The following packages will be UPDATED:\n",
      "\n",
      "  ca-certificates    pkgs/main::ca-certificates-2022.4.26-~ --> conda-forge::ca-certificates-2022.6.15-ha878542_0\n",
      "  certifi            pkgs/main::certifi-2022.5.18.1-py39h0~ --> conda-forge::certifi-2022.6.15-py39hf3d152e_0\n",
      "\n",
      "The following packages will be SUPERSEDED by a higher-priority channel:\n",
      "\n",
      "  openssl              pkgs/main::openssl-1.1.1o-h7f8727e_0 --> conda-forge::openssl-1.1.1o-h166bdaf_0\n",
      "\n",
      "\n",
      "\n",
      "Downloading and Extracting Packages\n",
      "wandb-0.12.18        | 1.3 MB    | ##################################### | 100% \n",
      "smmap-3.0.5          | 22 KB     | ##################################### | 100% \n",
      "shortuuid-1.0.8      | 17 KB     | ##################################### | 100% \n",
      "gitdb-4.0.9          | 46 KB     | ##################################### | 100% \n",
      "promise-2.3          | 36 KB     | ##################################### | 100% \n",
      "gitpython-3.1.27     | 123 KB    | ##################################### | 100% \n",
      "sentry-sdk-1.5.12    | 90 KB     | ##################################### | 100% \n",
      "pathtools-0.1.2      | 8 KB      |                                       |   0% WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/INSTALLER.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/AUTHORS.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/LICENSE.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/WHEEL.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/top_level.txt.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/RECORD.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/METADATA.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools/version.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools/patterns.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools/__init__.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools/path.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/licenses/LICENSE.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/test/run_test.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/recipe/meta.yaml.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/recipe/meta.yaml.template.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/recipe/conda_build_config.yaml.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/recipe/recipe_log.txt.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/paths.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/index.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/files.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/git.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/hash_input.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/about.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/repodata_record.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/link.json.  Please remove this file manually (you may need to reboot to free file handles)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/INSTALLER.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/AUTHORS.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/LICENSE.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/WHEEL.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/top_level.txt.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/RECORD.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools-0.1.2.dist-info/METADATA.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools/version.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools/patterns.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools/__init__.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/site-packages/pathtools/path.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/licenses/LICENSE.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/test/run_test.py.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/recipe/meta.yaml.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/recipe/meta.yaml.template.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/recipe/conda_build_config.yaml.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/recipe/recipe_log.txt.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/paths.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/index.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/files.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/git.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/hash_input.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/about.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/repodata_record.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1/info/link.json.  Please remove this file manually (you may need to reboot to free file handles)\n",
      "pathtools-0.1.2      | 8 KB      | ##################################### | 100% \n",
      "docker-pycreds-0.4.0 | 11 KB     | ##################################### | 100% \n",
      "setproctitle-1.2.3   | 16 KB     | ##################################### | 100% \n",
      "\n",
      "InvalidArchiveError('Error with archive /home/ubuntu/anaconda3/pkgs/pathtools-0.1.2-py_1.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\\n\\nCould not unlink')\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!conda install -c conda-forge wandb -y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "147f8f61",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "정상 : 400\n",
      "흰가루병 : 400\n",
      "점무늬병 : 400\n",
      "해충 : 400\n"
     ]
    }
   ],
   "source": [
    "root_dir = '/home/lab38/images'\n",
    "print('정상 :', len(os.listdir(os.path.join(root_dir,'로즈마리_정상'))))\n",
    "print('흰가루병 :', len(os.listdir(os.path.join(root_dir,'로즈마리_흰가루병'))))\n",
    "print('점무늬병 :', len(os.listdir(os.path.join(root_dir,'로즈마리_점무늬병'))))\n",
    "print('해충 :', len(os.listdir(os.path.join(root_dir,'로즈마리_해충'))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d02cc299",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:why] *",
   "language": "python",
   "name": "conda-env-why-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
